augmentation:
  degrees: 10.0
  flip_lr: 0.5
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  mosaic: 1.0
  scale: 0.5
  translate: 0.1
data:
  class_names: [] # 可选
  num_classes: 8
  train_images: /mnt/data/zxy/dataset/vedai_8/train.txt
  train_labels: /mnt/data/zxy/dataset/vedai_8/labels/visible
  val_images: /mnt/data/zxy/dataset/vedai_8/test.txt
  val_labels: /mnt/data/zxy/dataset/vedai_8/labels/visible
eval:
  conf_threshold: 0.25   
  iou_threshold: 0.5   
  nms_threshold: 0.45    
loss:
  lambda_box: 7.5
  lambda_cls: 0.5
  lambda_dfl: 1.5
model:
  backbone: cspdarknet_s  # resnet18, resnet34, resnet50, cspdarknet_n, cspdarknet_s, cspdarknet_m
  input_size:
  - 640
  - 640
  num_anchors: 1    
optimizer:
  lr_schedule: cosine
  type: SGD
train:
  batch_size: 16
  checkpoint_dir: checkpoints_vedai_8
  epochs: 200
  learning_rate: 0.01
  momentum: 0.937
  num_workers: 4
  resume: ''
  save_interval: 10   
  warmup_epochs: 3
  weight_decay: 0.0005

